// <auto-generated />
using System;
using BackEndOTP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndOTP.Migrations
{
    [DbContext(typeof(OTAPPContext))]
    [Migration("20211113023240_OTAPP")]
    partial class OTAPP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BackEndOTP.entity.Consulta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data")
                        .HasColumnType("TEXT");

                    b.Property<string>("especialidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("hopsital")
                        .HasColumnType("TEXT");

                    b.Property<int?>("hopsitalname")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("hora")
                        .HasColumnType("TEXT");

                    b.Property<int>("hospitalID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("usuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("hopsitalname");

                    b.HasIndex("usuarioID");

                    b.ToTable("consultas");
                });

            modelBuilder.Entity("BackEndOTP.entity.Hospital", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("hospital")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("hospitals");
                });

            modelBuilder.Entity("BackEndOTP.entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateDeNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("email", "cpf")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("BackEndOTP.entity.Consulta", b =>
                {
                    b.HasOne("BackEndOTP.entity.Hospital", "hospitalid")
                        .WithMany()
                        .HasForeignKey("hopsitalname");

                    b.HasOne("BackEndOTP.entity.Usuario", "Usuarioid")
                        .WithMany()
                        .HasForeignKey("usuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospitalid");

                    b.Navigation("Usuarioid");
                });
#pragma warning restore 612, 618
        }
    }
}
